// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHAKlM3R-c6o-jTRrcVWMBGOn01Hc_HXE',
    appId: '1:141331387563:web:d568f19ba88248870453ee',
    messagingSenderId: '141331387563',
    projectId: 'quizapp-a222f',
    authDomain: 'quizapp-a222f.firebaseapp.com',
    storageBucket: 'quizapp-a222f.appspot.com',
    measurementId: 'G-MS49R0Z1YD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMEAZGwB8IwOEjnM2vyMxS4C-W9KsN2Qw',
    appId: '1:141331387563:android:e507fec2e96aad870453ee',
    messagingSenderId: '141331387563',
    projectId: 'quizapp-a222f',
    storageBucket: 'quizapp-a222f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbCIllDhWHMhGbfnHHqCeUXxi-Be-LKKY',
    appId: '1:141331387563:ios:246e73d7302d22100453ee',
    messagingSenderId: '141331387563',
    projectId: 'quizapp-a222f',
    storageBucket: 'quizapp-a222f.appspot.com',
    iosBundleId: 'com.example.quizApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbCIllDhWHMhGbfnHHqCeUXxi-Be-LKKY',
    appId: '1:141331387563:ios:246e73d7302d22100453ee',
    messagingSenderId: '141331387563',
    projectId: 'quizapp-a222f',
    storageBucket: 'quizapp-a222f.appspot.com',
    iosBundleId: 'com.example.quizApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHAKlM3R-c6o-jTRrcVWMBGOn01Hc_HXE',
    appId: '1:141331387563:web:f759428e73a99f0f0453ee',
    messagingSenderId: '141331387563',
    projectId: 'quizapp-a222f',
    authDomain: 'quizapp-a222f.firebaseapp.com',
    storageBucket: 'quizapp-a222f.appspot.com',
    measurementId: 'G-SJL7EFHP8N',
  );
}
